[package]
name = "industrial-io"
version = "0.5.1"
edition = "2018"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/rust-industrial-io"
license = "MIT"
readme = "README.md"
keywords = ["linux", "embedded", "analog", "iio"]
categories = ["embedded", "hardware-support", "os", "os::unix-apis"]
description = """
Linux Industrial I/O (IIO) Support
"""

[dependencies]
libiio-sys = { version = "0.3", path = "libiio-sys" }
thiserror = "1.0"
nix = "0.16"
clap = "2.33"

[dev-dependencies]
schedule_recv = "0.1"
chrono = "0.4"
ctrlc = "3.1"
anyhow = "1.0"
