[package]
name = "industrial-io"
version = "0.1.0"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/rust-industrial-io"
license = "MIT"
keywords = ["linux", "embedded", "iio"]
categories = ["embedded", "hardware-support", "os", "os::unix-apis"]
description = """
Linux Industrial I/O (IIO) Support
"""

[dependencies]
libiio-sys = { path = "libiio-sys" }
error-chain = "0.12"
nix = "0.11"

[dev-dependencies]
schedule_recv = "0.1"

